openapi: 3.0.0
info:
  title: Email service abstraction API
  description: Email service API to provide an abstraction between different email
    service providers. Current supported providers Mailgun and SendGrid.
  contact:
    email: tolitest@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.1
servers:
- url: https://jk8ncbovj6.execute-api.us-east-2.amazonaws.com/test/
  description: Using test AWS instance.
tags:
- name: developers
  description: Operations available to regular developers
paths:
  /email:
    get:
      tags:
      - developers
      summary: Returns current status of email
      description: Sends email to service, service will make sure that one of providers
        will trigger email to customer.
      operationId: getEmailStatus
      parameters:
      - name: uuid
        in: query
        description: UUID of accepted email request
        required: false
        style: form
        explode: true
        schema:
          type: string
        example: 75fa9038-352d-463a-a053-1d9eca975cff
      responses:
        "200":
          description: Email status
        "400":
          description: Invalid request body
        "404":
          description: Not found
    post:
      tags:
      - developers
      summary: Sends email to customer
      description: Sends email to service, service will deliver request to one of
        providers, valid email will be sent to customer.
      operationId: sendEmail
      requestBody:
        description: Sends email to recipients
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Email'
      responses:
        "200":
          description: Email accepted, response return Email status
        "400":
          description: Invalid request body
components:
  schemas:
    Email:
      required:
      - body
      - from
      - subject
      - to
      type: object
      properties:
        from:
          maxLength: 250
          minLength: 4
          type: string
          format: email
          example: your@email.com
        to:
          maximum: 100
          minimum: 1
          type: array
          example:
          - your@email.com
          - your@email.com
          items:
            maxLength: 250
            minLength: 4
            type: string
            format: email
        cc:
          maximum: 100
          type: array
          example:
          - your@email.com
          - your@email.com
          items:
            maxLength: 250
            minLength: 4
            type: string
            format: email
        bcc:
          maximum: 100
          type: array
          example:
          - your@email.com
          - your@email.com
          items:
            maxLength: 250
            minLength: 4
            type: string
            format: email
        subject:
          maxLength: 250
          minLength: 1
          type: string
          example: Subject!
        body:
          maxLength: 1000
          minLength: 1
          type: string
          example: Body!
    EmailStatus:
      type: object
      properties:
        uuid:
          type: string
          example: dec1bfba-8c15-42b3-b5ff-154daa8f7c66
        provider:
          type: string
          example: SENDGRID
          enum:
          - SENDGRID
          - MAILGUN
        state:
          type: string
          example: ACCEPTED
          enum:
          - ACCEPTED
          - FAILED
          - BAD_REQUEST
          - SUCCESS
