openapi: 3.0.0
info:
  title: Email service abstraction API
  description: Email service API to provide an abstraction between different email
    service providers. Current supported providers Mailgun and SendGrid.
  contact:
    email: tolitest@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.1
servers:
- url: https://virtserver.swaggerhub.com/ToliTest/EmailService/1.0.0
  description: Using SwaggerHub API Auto Mocking during contract desing.
tags:
- name: admins
  description: Secured Admin-only calls
- name: developers
  description: Operations available to regular developers
paths:
  /email:
    post:
      tags:
      - developers
      summary: Sends email to customer
      description: Sends email to service, service will make sure that one of providers
        will trigger email to customer.
      operationId: sendEmail
      requestBody:
        description: Sends email to recipients
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Email'
      responses:
        "200":
          description: Email queued
        "201":
          description: Email queued
        "400":
          description: invalid input, object invalid
components:
  schemas:
    Email:
      required:
      - body
      - from
      - subject
      - to
      type: object
      properties:
        from:
          maxLength: 250
          minLength: 4
          type: string
          format: email
          example: your@email.com
        to:
          maximum: 100
          minimum: 1
          type: array
          example:
          - your@email.com
          - your@email.com
          items:
            maxLength: 250
            minLength: 4
            type: string
            format: email
        cc:
          maximum: 100
          type: array
          example:
          - your@email.com
          - your@email.com
          items:
            maxLength: 250
            minLength: 4
            type: string
            format: email
        bcc:
          maximum: 100
          type: array
          example:
          - your@email.com
          - your@email.com
          items:
            maxLength: 250
            minLength: 4
            type: string
            format: email
        subject:
          maxLength: 250
          minLength: 1
          type: string
          example: Subject!
        body:
          maxLength: 1000
          minLength: 1
          type: string
          example: Body!
